// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDO5BhRZ6dOGVEWwEPtc3SCv4yCw37p0L0',
    appId: '1:448437059603:web:32059bbc6a6b29e1ab3fe6',
    messagingSenderId: '448437059603',
    projectId: 'iot-bike-lock',
    authDomain: 'iot-bike-lock.firebaseapp.com',
    databaseURL: 'https://iot-bike-lock-default-rtdb.firebaseio.com',
    storageBucket: 'iot-bike-lock.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7ww8p_uUpjq-Rlbjgjr03NYxZFdWj8LI',
    appId: '1:448437059603:android:84f51ee44a15c85fab3fe6',
    messagingSenderId: '448437059603',
    projectId: 'iot-bike-lock',
    databaseURL: 'https://iot-bike-lock-default-rtdb.firebaseio.com',
    storageBucket: 'iot-bike-lock.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBLeqzoZIZYpmZgxq8jzTSi0pzlm7nrl5U',
    appId: '1:448437059603:ios:3e7909008422cad5ab3fe6',
    messagingSenderId: '448437059603',
    projectId: 'iot-bike-lock',
    databaseURL: 'https://iot-bike-lock-default-rtdb.firebaseio.com',
    storageBucket: 'iot-bike-lock.appspot.com',
    iosClientId: '448437059603-i52c5con5m4i66prbddguec24oqgv8f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.bikeLockApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBLeqzoZIZYpmZgxq8jzTSi0pzlm7nrl5U',
    appId: '1:448437059603:ios:3e7909008422cad5ab3fe6',
    messagingSenderId: '448437059603',
    projectId: 'iot-bike-lock',
    databaseURL: 'https://iot-bike-lock-default-rtdb.firebaseio.com',
    storageBucket: 'iot-bike-lock.appspot.com',
    iosClientId: '448437059603-i52c5con5m4i66prbddguec24oqgv8f1.apps.googleusercontent.com',
    iosBundleId: 'com.example.bikeLockApp',
  );
}
